export default {
    safelist: [
        "bg-red", "text-red", "border-red",
        "bg-crimson", "text-crimson", "border-crimson",
        "bg-rose", "text-rose", "border-rose",
        "bg-pink", "text-pink", "border-pink",
        "bg-magenta", "text-magenta", "border-magenta",
        "bg-fuchsia", "text-fuchsia", "border-fuchsia",
        "bg-purple", "text-purple", "border-purple",
        "bg-violet", "text-violet", "border-violet",
        "bg-indigo", "text-indigo", "border-indigo",
        "bg-blue", "text-blue", "border-blue",
        "bg-azure", "text-azure", "border-azure",
        "bg-sky", "text-sky", "border-sky",
        "bg-cyan", "text-cyan", "border-cyan",
        "bg-teal", "text-teal", "border-teal",
        "bg-mint", "text-mint", "border-mint",
        "bg-emerald", "text-emerald", "border-emerald",
        "bg-green", "text-green", "border-green",
        "bg-lime", "text-lime", "border-lime",
        "bg-chartreuse", "text-chartreuse", "border-chartreuse",
        "bg-yellow", "text-yellow", "border-yellow",
        "bg-amber", "text-amber", "border-amber",
        "bg-orange", "text-orange", "border-orange",
        "bg-tangerine", "text-tangerine", "border-tangerine",
        "bg-salmon", "text-salmon", "border-salmon",

        "bg-lightpink", "text-lightpink", "border-lightpink",
        "bg-lavender", "text-lavender", "border-lavender",
        "bg-lightblue", "text-lightblue", "border-lightblue",
        "bg-lightcyan", "text-lightcyan", "border-lightcyan",
        "bg-lightgreen", "text-lightgreen", "border-lightgreen",
        "bg-lightyellow", "text-lightyellow", "border-lightyellow",
        "bg-peach", "text-peach", "border-peach",
        "bg-coral", "text-coral", "border-coral"
    ],
};
